version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app_network

  scylla:
    image: scylladb/scylla
    container_name: scylla
    environment:
      - SCYLLA_CLUSTER_NAME=universal_cluster
      - SCYLLA_LISTEN_ADDRESS=0.0.0.0
      - SCYLLA_BROADCAST_ADDRESS=scylla
      - SCYLLA_RPC_ADDRESS=0.0.0.0
      - SCYLLA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    ports:
      - "9042:9042"  # CQL port
      - "7001:7001"  # Cluster communication port
    volumes:
      - scylla_data:/var/lib/scylla
    networks:
      - app_network

volumes:
  scylla_data:

networks:
  app_network:
    driver: bridge
