name: Build and deploy Grading and Commons JAR apps to Azure Web Apps

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'


      - name: Install Parent POM
        run: mvn -N clean install

      - name: Build and install Commons module
        run: mvn -pl commons clean install

      # Step 3: Build Grading module
      - name: Build Grading module
        run: mvn -pl grading clean install

      # Upload Grading artifact
      - name: Upload Grading artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: grading-app
          path: 'grading/target/grading-0.0.1-SNAPSHOT.jar'

      # Step 4: Build Examination module
      - name: Build Examination module
        run: mvn -pl examination clean install

      # Upload Examination artifact
      - name: Upload Examination artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: examination-app
          path: 'examination/target/examination-0.0.1-SNAPSHOT.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:

      - name: Download Grading artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: grading-app

      - name: Deploy Grading JAR to Azure Web App
        id: deploy-grading
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'INNO-testvision-grading'
          slot-name: 'Production'
          package: 'grading-0.0.1-SNAPSHOT.jar'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3AC5B4C41514457FBE064F33BD70B76C }}


      - name: Download Examination artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: examination-app

      - name: Deploy Examination JAR to Azure Web App
        id: deploy-examination
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'examination'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C425286D981E4D8480B8051376B3814E }}
          package: 'examination-0.0.1-SNAPSHOT.jar'