name: Build and deploy Grading JAR app to Azure Web App

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      - name: Upload Grading JAR artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: grading-module
          path: grading/target/grading-0.0.1-SNAPSHOT.jar

      - name: Upload encrypted secrets.properties
        uses: actions/upload-artifact@v4
        with:
          name: encrypted-secrets-file
          path: encrypted/secrets.properties.gpg

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: grading-module

      - name: Download encrypted secrets.properties file
        uses: actions/download-artifact@v4
        with:
          name: encrypted-secrets-file

      - name: Decrypt secrets.properties
        run: |
          gpg --batch --passphrase "$GPG_PASSPHRASE" --decrypt \
          --output secrets.properties encrypted/secrets.properties.gpg
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Set secrets as environment variables
        run: |
          export $(grep -v '^#' secrets.properties | xargs)

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'INNO-testvision-grading'
          slot-name: 'Production'
          package: grading-0.0.1-SNAPSHOT.jar
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_73515D5397D34CAB8FB1E26C38C3FA25 }}